server:
  port: 9091
spring:
  application:
    name: Product Microservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping
  profiles:
    active:
    - local
  boot:
    admin:
      client:
        url:
        - http://localhost:9999
product:
  currency:
  - INR
  - USD
  - EUR
  - DINR
logging:
  file:
    name: ./logs/product.log
  rollingpolicy:
    max-file-size:
    - 5mb
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: ALWAYS