server:
  port: 9091
spring:
  application:
    name: Product Microservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping
  profiles:
    active:
    - test
product:
  currency:
  - INR
  - USD
  - EUR
  - DINR
  
---
server:
  port: 9094

spring:
  config:
    activate:
      on-profile:
      - test
      
logging:
    file:
      name: ./logs/product.log
    
    rollingpolicy:
      max-file-size:
        - 5mb
      