server:
  port: 9999
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sunku.dinesh9@gmail.com
    password: SUDHAKARgupta
    test-connection: true
  boot:
    admin:
      notify:
        mail:
          to:
          - vamsi.tharun4@gmail.com
          ignore-changes:
          - ''